server: 
  port: 9001
eureka: 
  instance:
    hostname: consumer01
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://lijingyu:lijingyu@eureka01:7901/eureka/,http://eureka02:7902/eureka/
spring:
  application:
    #应用名称
    name: EurekaConsumer