server: 
  port: 7902
eureka: 
  instance:
    #eureka名称
    hostname: eureka02
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://lijingyu:lijingyu@eureka01:7901/eureka/
spring:
  application:
    #应用名称
    name: EurekaServer