server: 
  port: 7901
eureka: 
  instance:
    #eureka名称
    appname: eureka01
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://eureka02:7902/eureka/
spring:
  application:
    #应用名称
    name: eureka01