server: 
  port: 7901
eureka: 
  server:
    #关闭自我保护机制
    enable-self-preservation: false
  instance:
    #eureka名称 主机名
    hostname: eureka01
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://eureka02:7902/eureka/
#    fetch-registry: false
#    register-with-eureka: false
spring:
  application:
    #应用名称 集群环境下，多个节点的名称需要保持一致
    name: EurekaServer
  security:
    user:
      name: lijingyu
      password: lijingyu