server:
  port: 8001
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:/ProjectDev/P8-Project1/Project1/RealProject/SpringCloud-Netflix/localConfig
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://server02:4002/eureka,http://server01:4001/eureka
