server: 
  port: 9001
management:
  endpoints:
    web:
      exposure:
      #暴露所有节点
        include:
        - '*'
eureka: 
  instance:
    hostname: consumer01
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://lijingyu:lijingyu@eureka01:7901/eureka/,http://eureka02:7902/eureka/
    healthcheck:
      enabled: true
spring:
  application:
    #应用名称
    name: EurekaConsumer
feign:
  client: 
    config:  
      service-valuation: 
      #记录日志
        logger-level: full
  hystrix:
    enabled: true